project_id = "rimpknatyinpcgtxltfm"

[functions.drgreen-proxy]
verify_jwt = false

[functions.drgreen-health]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-onboarding-email]
verify_jwt = false

[functions.send-client-email]
verify_jwt = false

[functions.drgreen-webhook]
verify_jwt = false

[functions.prescription-expiry-check]
verify_jwt = false

[functions.strain-medical-info]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false
