project_id = "drouwihrfyjmoyocwqxh"

[functions.drgreen-proxy]
verify_jwt = false

[functions.drgreen-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.sync-strains]
verify_jwt = false

[functions.prescription-expiry-check]
verify_jwt = false
